apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-system
spec:
  releaseName: istio-ingress
  chart:
    repository: https://istio-release.storage.googleapis.com/charts
    name: istio-ingress
    version: 1.10.0
  values:
    gateways:
      istio-ingressgateway:
        enabled: true
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-type: nlb
        type: LoadBalancer
        ports:
          - port: 80
            targetPort: 80
            name: http
          - port: 443
            targetPort: 443
            name: https
    global:
      istioNamespace: istio-system
      proxy:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 526Mi