apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  releaseName: istio-base
  interval: 5m
  chart:
    spec:
      chart: istio-base
      version: 1.19.0
      sourceRef:
        kind: HelmRepository
        name: istio-helm-repo
        namespace: flux-system
  values:
    global:
      istioNamespace: istio-system
