apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: flux-system
spec:
  releaseName: istio-ingress
  interval: 10m
  dependsOn:
    - name: istio-base
      namespace: flux-system
    - name: istiod
      namespace: flux-system
  chart:
    spec:
      chart: gateway
      version: 1.24.0
      sourceRef:
        kind: HelmRepository
        name: istio-helm-repo
        namespace: flux-system
  values:
    service:
      type: LoadBalancer
      ports:
      - port: 80
        targetPort: 80
        name: http
      - port: 443
        targetPort: 443
        name: https
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 526Mi