apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: istio-base
      namespace: flux-system
  chart:
    spec:
      chart: istiod
      version: 1.24.0
      sourceRef:
        kind: HelmRepository
        name: istio-helm-repo
        namespace: flux-system
      interval: 1m