apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-system
spec:
  releaseName: istio-ingress
  interval: 10m
  install:
    disableOpenAPIValidation: true
  upgrade:
    disableOpenAPIValidation: true
  dependsOn:
    - name: istio-base
      namespace: istio-system
    - name: istiod
      namespace: istio-system
  chart:
    spec:
      chart: gateway
      version: 1.24.0
      sourceRef:
        kind: HelmRepository
        name: istio-helm-repo
        namespace: flux-system
  values:
    labels:
      app: istio-ingressgateway
      istio: ingressgateway
    nodeSelector:
      ingress: "true"
    service:
      type: NodePort
      ports:
      - name: status-port
        port: 15021
        protocol: TCP
        targetPort: 15021
      - name: http2
        port: 80
        protocol: TCP
        targetPort: 80
        nodePort: 30080
      - name: https
        port: 443
        protocol: TCP
        targetPort: 443
        nodePort: 30443
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 526Mi