apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-hello-world-api
  labels:
    app: dotnet-hello-world-api
spec:
  selector:
    matchLabels:
      app: dotnet-hello-world-api
  template:
    metadata:
      labels:
        app: dotnet-hello-world-api
    spec:
      containers:
      - name: dotnet-hello-world-api
        image: ghcr.io/seregazh/dotnet-hello-world-api:0.0.20
