apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/dotnet-hello-world-api
patches:
  - path: dotnet-hello-world-api-values.yaml
    target:
      kind: Deployment