apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flux-applier-secrets
  namespace: istio-system
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-applier-secrets-binding
  namespace: istio-system
subjects:
  - kind: ServiceAccount
    name: flux-applier
    namespace: istio-system
roleRef:
  kind: Role
  name: flux-applier-secrets
  apiGroup: rbac.authorization.k8s.io
