apiVersion: v1
kind: ServiceAccount
metadata:
  name: kiali-user
  namespace: istio-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kiali-view-role
  namespace: istio-system
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kiali-view-binding
  namespace: istio-system
subjects:
  - kind: ServiceAccount
    name: kiali-user
    namespace: istio-system
roleRef:
  kind: Role
  name: kiali-view-role
  apiGroup: rbac.authorization.k8s.io