apiVersion: v1
kind: ServiceAccount
metadata:
  name: kiali-user
  namespace: istio-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kiali-view-role
  namespace: istio-system
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kiali-view-binding
  namespace: istio-system
subjects:
  - kind: ServiceAccount
    name: kiali-user
    namespace: istio-system
roleRef:
  kind: Role
  name: kiali-view-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kiali-view-cluster-role
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.istio.io", "security.istio.io", "extensions.istio.io", "telemetry.istio.io", "gateway.networking.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "delete", "patch"]
- apiGroups: [""]
  resources: ["configmaps", "endpoints", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["namespaces", "pods", "replicationcontrollers", "services"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["create", "post"]
- apiGroups: ["extensions", "apps"]
  resources: ["daemonsets", "deployments", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: ["batch"]
  resources: ["cronjobs", "jobs"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["create"]
- apiGroups: ["", "extensions", "apps", "networking.istio.io"]
  resources: ["pods", "services", "deployments", "virtualservices", "gateways"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["config.istio.io", "networking.istio.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kiali-view-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: kiali
  namespace: istio-system
roleRef:
  kind: ClusterRole
  name: kiali-view-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: kiali-user
  namespace: istio-system
  annotations:
    kubernetes.io/service-account.name: kiali-user
type: kubernetes.io/service-account-token