apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-resources-test
  labels:
    app: dotnet-resources-test
spec:
  selector:
    matchLabels:
      app: dotnet-resources-test
  template:
    metadata:
      labels:
        app: dotnet-resources-test
    spec:
      containers:
      - name: dotnet-resources-test
        image: ghcr.io/seregazh/dotnet-hello-world-api:0.0.21
        resources:
          requests:
            memory: "60Mi"
            cpu: "50m"
          limits:
            memory: "120Mi"
            cpu: "100m"
