apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-resources-test
  labels:
    app: dotnet-resources-test
spec:
  selector:
    matchLabels:
      app: dotnet-resources-test
  template:
    metadata:
      labels:
        app: dotnet-resources-test
    spec:
      containers:
      - name: dotnet-resources-test
        image: sztestacr.azurecr.io/dotnet-resources-test:0.0.6
        resources:
          requests:
            memory: "3024Mi"
            cpu: "50m"
          limits:
            memory: "3024Mi"
            cpu: "50m"
